[project]
name = "ep002-checkpoints"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "tenacity>=9.0.0",
]
